# Name override instead of fullname (helm-webapp-cve-processor)
nameOverride: 'cve-processor'

# Docker Hub credentials secret
secrets:
  dockerhubconfigjson: ''

env: 
  KAFKA_BROKERS: "localhost:9092,localhost:9093,localhost:9094"
  KAFKA_TOPIC: "test_topic1"
  KAFKA_CONSUMER_GROUP_ID: "cve"
  KAFKA_MAX_SIZE: "10e6"
  PORT: "3001"

initContainers:
  - name: 'db-migrate'
    repository: marlapativ/db-migration
    tag: 'latest'
    pullPolicy: Always
    command: ['flyway']
    args: ['migrate']

podLabels: {}

serviceAccount:
  create: true
  name: 'webapp-cve-consumer-sa'
  automount: true
  annotations: {}

db:
  secrets:
    username: ''
    password: ''
    database: ''
  config:
    port: '5432'

kafka:
  secrets:
    username: ''
    password: ''  

replicaCount: 3

image:
  repository: marlapativ/webapp-cve-consumer
  tag: 'latest'
  pullPolicy: Always
