apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-webapp-cve-consumer.fullname" . }}-deployment
  namespace: '{{ .Release.Namespace }}'
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-webapp-cve-consumer.selectorLabels" . | nindent 6 }}
      {{- with .Values.podLabels }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
  template:
    metadata:
      labels:
        {{- include "helm-webapp-cve-consumer.selectorLabels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "helm-webapp-cve-consumer.serviceAccountName" . }}
      restartPolicy: OnFailure
      imagePullSecrets:
        - name: {{ include "helm-webapp-cve-consumer.fullname" . }}-secrets

      initContainers:
        {{- range .Values.initContainers }}
        - name: {{ .name }}
          image: "{{ .repository }}:{{ .tag | default "latest" }}"
          imagePullPolicy: {{ .pullPolicy | default "Always" }}
          command: {{ .command }}
          args: {{ .args }}
          envFrom:
            - secretRef:
                name: {{ include "helm-webapp-cve-consumer.fullname" $ }}-db-secrets
        {{- end }}

      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        imagePullPolicy: {{ .Values.image.pullPolicy | default "Always" }}
        envFrom:
          - secretRef:
              name: {{ include "helm-webapp-cve-consumer.fullname" . }}-consumer-secrets
          - configMapRef:
              name: {{ include "helm-webapp-cve-consumer.fullname" . }}-consumer-configmap
