{{- $replicaCount := int .Values.replicaCount }}
{{- if .Values.autoscaling.hpa.enabled }}
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "helm-webapp-cve-consumer.fullname" . }}-deployment
  namespace: '{{ .Release.Namespace }}'
  labels:
    {{- include "helm-webapp-cve-consumer.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "helm-webapp-cve-consumer.fullname" . }}-deployment
  minReplicas: {{ .Values.autoscaling.hpa.minReplicas }}
  maxReplicas: {{ .Values.autoscaling.hpa.maxReplicas }}
  metrics:
    {{- if .Values.autoscaling.hpa.targetCPU }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.hpa.targetCPU }}
    {{- end }}
    {{- if .Values.autoscaling.hpa.targetMemory }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.autoscaling.hpa.targetMemory }}
    {{- end }}
{{- end }}
